AWSTemplateFormatVersion: 2010-09-09
Parameters:
  FrontEndGHRepo:
    Type: String
    Default: "OMGITSPHOTOS"

  FrontEndGHBranch:
    Type: String
    Default: "front-end"

  FrontEndGHToken:
    Type: String
    Default: ""

  FrontEndGHUser:
    Type: String
    Default: "gloriahwoang"

  LambdasGHRepo:
    Type: String
    Default: "OMGITSPHOTOS"

  LambdasGHBranch:
    Type: String
    Default: "main"

  LambdasGHToken:
    Type: String
    Default: ""

  LambdasGHUser:
    Type: String
    Default: "gloriahwoang"

Resources:
  AdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
                - codepipeline.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: admin
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  S3ForArtifact:
    Type: "AWS::S3::Bucket"

  S3Frontend:
    Type: "AWS::S3::Bucket"

  LambdasPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      RoleArn: !GetAtt AdminRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref S3ForArtifact
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "2"
              RunOrder: 1
              Configuration:
                Repo: !Ref LambdasGHRepo
                Branch: !Ref LambdasGHBranch
                OAuthToken: !Ref LambdasGHToken
                Owner: !Ref LambdasGHUser
                PollForSourceChanges: "true"
              OutputArtifacts:
                - Name: SourceArtifact
              InputArtifacts: []
              Region: "us-east-1"
              Namespace: SourceVariables
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              RunOrder: 1
              Configuration:
                ProjectName: "lambda-pipeline-build"
              OutputArtifacts:
                - Name: BuildArtifact
              InputArtifacts:
                - Name: SourceArtifact
              Region: "us-east-1"
              Namespace: BuildVariables
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              RunOrder: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                ChangeSetName: "asm2-changeset"
                RoleArn: !GetAtt AdminRole.Arn
                StackName: "omgitsphotos-stack"
                TemplatePath: BuildArtifact::output-sam.yml
              OutputArtifacts: []
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-east-1
              Namespace: DeployVariables

  PipelineS3:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      RoleArn: !GetAtt AdminRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref S3ForArtifact
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Repo: !Ref FrontEndGHRepo
                Owner: !Ref FrontEndGHUser
                Branch: !Ref FrontEndGHBranch
                OAuthToken: !Ref FrontEndGHToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                BucketName: !Ref S3Frontend
                Extract: true
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

  OpenSearch:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
          MasterUserOptions: 
              MasterUserName: admin
              MasterUserPassword: admin
      NodeToNodeEncryptionOptions: 
        Enabled: true
      EncryptionAtRestOptions:
        Enabled: true
      DomainEndpointOptions: 
        EnforceHTTPS : true
      DomainName: 'photos-asm2'
      ClusterConfig:
        InstanceCount: '1'
        InstanceType: 't3.small.search'
      EBSOptions:
        EBSEnabled: true
        Iops: '3000'
        VolumeSize: '10'
        VolumeType: 'gp3'
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'