AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: OMGITSPHOTOS Lambdas
Resources:
  s3forPhoto:
    Type: AWS::S3::Bucket
    Properties:s
      BucketName: asm2
  LF1-indexPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LF1-indexPhotos
      Handler: LF1-indexPhotos.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambdas
      Description: 'LF1 for indexing photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::653496211370:role/LambdaASM2'
      Layers:
        - arn:aws:lambda:us-east-1:653496211370:layer:aws4auth:1
        - arn:aws:lambda:us-east-1:653496211370:layer:6998asm1db:1
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket:
              Ref: asm2
            Events: s3:ObjectCreated:Put
      Environment:
        Variables:
          REGION: us-east-1
  LF2-searchPhotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LF2-Search-Photos
      Handler: LF2-Search-Photos.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambdas
      Description: 'LF2 for searching photos'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::653496211370:role/LambdaASM2'
      Environment:
        Variables:
          REGION: us-east-1
      Layers:
        - arn:aws:lambda:us-east-1:653496211370:layer:6998asm1db:1
        - arn:aws:lambda:us-east-1:653496211370:layer:aws4auth:1
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: get
        putAZsAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: put