version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file sam.yaml --s3-bucket asm2-pipeline-lambda --output-template-file output-sam.yml
artifacts:
  type: zip
  files:
    - sam.yaml
    - output-sam.yml