version: 0.2
environment_variables:
    plaintext:
        "INPUT_FILE": "sam.yaml"
        "S3_BUCKET": ""
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template output-sam.yaml
        artifacts:
            files:
                - output-sam.yaml