Transform: 'AWS::Serverless-2016-10-31'
Description: OMGITSPHOTOS Lambdas
Resources:
    webBackend:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs4.3
            CodeUri: ../
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /
                  Method: ANY

    LF1-indexPhotos:
		  Type: 'AWS::Serverless::Function'
		  Properties:
          Handler: LF1-Index-Photos.lambda_handler
          Runtime: python3.7
          CodeUri: ./
          Description: LF1 for indexing photos
          MemorySize: 128
          Timeout: 30
          Role: arn:aws:iam::653496211370:role/LambdaASM2
			    Events:
            GetResource:
              Type: Api
              Properties:
                Path: /upload
                Method: put
          Environments:
				      Variables:
                    REGION: us-east-1

    LF2-searchPhotos:
        Type: 'AWS::Serverless::Function'
        Properties:
          Handler: LF2-Search-Photos.lambda_handler
          Runtime: python3.7
          CodeUri: ./
          Description: LF2 for searching photos
          MemorySize: 128
          Timeout: 30
          Role: arn:aws:iam::653496211370:role/LambdaASM2
			    Events:
            GetResource:
              Type: Api
              Properties:
                Path: /search
                Method: get
          Environments:
				      Variables:
                    REGION: us-east-1